function slider = drawslider(gui,row,scale,nRows)
%
% (C) Ann Kennedy, 2019
% California Institute of Technology
% Licensing: https://github.com/annkennedy/bento/blob/master/LICENSE.txt



slider.panel = uipanel('parent',gui.ctrl.panel,...
        'position',[0.01 (row-.5)/(nRows+1) 0.98 scale/(nRows+1)],'bordertype','none');

slider.Value      = 1;
slider.Min        = 1;
slider.Max        = 2;
slider.Scale      = 1-.015; %extra term corrects for marker width
slider.SliderStep = [1 1];
slider.Pos        = gui.ctrl.panel.Position .* slider.panel.Position;
slider.arrowW     = 0.025;
slider.textW      = 0.125;
slider.timer      = tic;

aW = slider.arrowW;
tW = slider.textW;

%make the slider
slider.LeftArrow = uipanel('Position',[0 0.05 aW 0.95],...
                'parent',slider.panel,...
                'backgroundcolor',[.92 .92 .92],...
                'bordertype','line',...
                'HighlightColor',[.5 .5 .5],...
                'tag','leftArrow',...
                'buttondownfcn',{@sliderCheck,gui.h0});
makeButton(slider.LeftArrow,char(9664));


slider.RightArrow = uipanel('Position',[1-aW-tW 0.05 aW 0.95],...
                'parent',slider.panel,...
                'backgroundcolor',[.92 .92 .92],...
                'bordertype','line',...
                'HighlightColor',[.5 .5 .5],...
                'tag','rightArrow',...
                'buttondownfcn',{@sliderCheck,gui.h0});
makeButton(slider.RightArrow,char(9656));


slider.Ctr        = uipanel('position',[aW 0.05 1-2*aW-tW 0.95],...
                'parent',slider.panel,...
                'bordertype','line',...
                'HighlightColor',[.5 .5 .5],...
                'tag','bar',...
                'buttondownfcn',{@sliderCheck,gui.h0});
axes('parent',slider.Ctr,'position',[.015/2 0 1-.015 1]);
slider.bg    = imagesc([],'hittest','off'); axis tight; axis off;


slider.Marker     = uipanel('position',[slider.Value*slider.Scale 0.05 .015 0.9],...
                'Parent',slider.Ctr,...
                'bordertype','line',...
                'HighlightColor',.7*ones(1,3),...
                'tag','marker',...
                'buttondownfcn',{@sliderCheck,gui.h0});
makeButton(slider.Marker,'');



%make the text box
slider.text   = uicontrol('Style','edit',...
            'String','',...
            'parent',slider.panel,...
            'units','normalized',...
            'position',[1-tW 0.05 .95*tW*.8 0.95],...
            'Tag','timeBox',...
            'Callback',@updatePlot);
slider.units  = uicontrol('Style','pushbutton',...
            'string',char(8644),...
            'parent',slider.panel',...
            'units','normalized',...
            'position',[1-tW*.2 0.075 .95*tW*.2 0.9],...
            'Tag','toggleTime',...
            'TooltipString','Switch to frame # (behavior video)',...
            'Callback',@changeTimeUnits);


