function MARSoptions(source,~)
gui     = guidata(source);

stims   = {};
for i=1:length(gui.allPopulated)
    m       = gui.allPopulated(i,1);
    sess    = ['session' num2str(gui.allPopulated(i,2))];
    tr      = gui.allPopulated(i,3);
    stims{i} = gui.allData(m).(sess)(tr).stim;
end
trialList = strcat({'mouse '}, num2str(gui.allPopulated(:,1)),...
                   { ', session '}, num2str(gui.allPopulated(:,2)),...
                   { ', trial '}, num2str(gui.allPopulated(:,3)),'  (');
trialList = strcat(trialList,stims',')');

hfig = figure(9876);clf;
style = {'units','normalized','fontsize',10};

set(hfig,'dockcontrols','off','menubar','none',...
    'NumberTitle','off','Position', hfig.Position.*[.8 1 1.5 .75],...
    'units','normalized','Tag','trainMARS');

uicontrol('parent',hfig,'style','pushbutton',style{:},...
    'position',[.725 .605 .225 .3],'backgroundcolor',[.65 1 .65],...
    'string','Retrain MARS','callback',@callMARS)

h1 = uipanel('parent',hfig,style{:},'position',[.025 .65 .7 .3],...
    'bordertype','none','title','Classifier settings',...
    'fontangle','italic','foregroundcolor',[.5 .5 .5]);
uicontrol('parent',h1,style{:},'style','text','position',[.025 .675 .1 .3],...
    'string','Name');
h.pth = uicontrol('parent',h1,style{:},'style','edit','position',[.025 .375 .825 .35],...
    'string','','horizontalalign','left');
uicontrol('parent',h1,style{:},'style','pushbutton','position',[.865 .375 .09 .35],...
    'string','...','callback',@pickMARSmodel);

h.train = uibuttongroup('parent',h1,style{:},'Position',[0 0 1 .3],'bordertype','none');              
uicontrol(h.train,style{:},'Style','radiobutton','String','Quick retrain',...
                  'position',[.025 0 .3 1]);
uicontrol(h.train,style{:},'Style','radiobutton','String','Full retrain',...
                  'position',[.3 0 .3 1]);
uicontrol(h.train,style{:},'Style','radiobutton','String','Make new classifier',...
                  'position',[.575 0 .4 1],'enable','off');




h2 = uipanel('parent',hfig,style{:},'position',[.025 .055 .95 .55],...
    'bordertype','none','title','New training data',...
    'fontangle','italic','foregroundcolor',[.5 .5 .5]);

uicontrol('parent',h2,style{:},'style','text','position',[.025 .775 .3 .2],...
    'string','Retrain behaviors:','horizontalalign','left');
h.bhvrs = uicontrol('parent',h2,style{:},'style','listbox','position',[.025 .1 .375 .75],...
    'string',{'attack','mount','investigation'},'min',1,'max',3);

uicontrol('parent',h2,style{:},'style','text','position',[.425 .775 .3 .2],...
    'string','Retrain from trials:','horizontalalign','left');
h.trials = uicontrol('parent',h2,style{:},'style','listbox','position',[.425 .1 .525 .75],...
    'string',trialList,'min',1,'max',length(trialList));

h.h0 = gui.h0;
guidata(hfig,h);