function mh = menu_setup(gui)

labels = char('&File',...
                 '>L&oad experiment^o',...
                 '>&Edit experiment^e',...
                 '>-------',...
                 '>Manage annotations',...
                 '>-------',...
                 '>Manage tracking data',...
                 '>Zoom movie in',...
                 '>Revert zoom',...
                 '>-------',...
                 '>Save screenshot',...
                 '>Save this movie frame',...
                 '>Save movie',...
                 '>-------',...
                 '>Quit',...
             '&Annotations',...
                 '>Set annotation &colors^c',...
                 '>Set annotation &hotkeys^h',...
                 '>Fix annot timing',...
                 '>Change annot framerate',...
             '&Display',...
                 '>Select &traces to show^t',...
                 '>Select a&nnotations to show^n',...
                 '>-------',...
                 '>Plot 2d projection',...
                 '>Clear 2d projection',...
                 '>-------',...
                 '>Toggle object &visibility^v',...
                 '>-------',...
                 '>Adjust &audio scaling^a',...
                 '>Adjust &movie scaling^m',...
                 '>-------',...
                 '>Sort units by CP',...
                 '&Help',...
                 '>Annotation s&hortcuts^h');
             
calls = char('','loadExpt(gcf,[],''load'')','loadExpt(gcf,[],''edit'')',...
             '','launchAnnotEditor(gcf,[])',...
             '','launchTrackingCleanup(gcf)','cropMovie(gcf,[],''crop'')','cropMovie(gcf,[],''revert'')',...
             '','saveScreen(gcf,0)','saveScreen(gcf,1)',...
                'saveMovie(gcf)',...
             '','doQuit(gcf)',...
             ...
             '','launchColorPick(gcf,[])',...
                'setAnnotHotkeys(gcf,[])',...
                'bumpAnnot(gcf)',...
                'launchAnnoChanger(gcf)',...
             '','pickUnits(gcf)','pickAnnot(gcf)',...
             '','setScatterDims(gcf)',...
                'clearScatterDims(gcf)',...
             '','toggleEnabled(gcf)','',...
                'setAudioThresholds(gcf)',...
                'setMovieBrightness(gcf)',...
             '','runCPsort(gcf)',...
             '','openHelpMenu(gcf)');

mh.display = makemenu(gui.h0,labels,calls);

% mh.analyze = uimenu(gui.h0,'Label','Analysis','enable','off');
% uimenu(mh.analyze,'Label','Find similar events','callback',{@(x,y) disp('not implemented yet')});
% uimenu(mh.analyze,'Label','Compute BTA','callback',@launchBTA);