function saveScreen(source,~)

gui = guidata(source);

[FileName,PathName] = uiputfile(...
{'*.eps;', 'EPS file (*.eps)';...
 '*.bmp', 'Bitmap file (*.bmp)';...
 '*.jpg', 'JPEG image (*.jpg)';...
 '*.fig','MATLAB Figure (*.fig)';...
 '*.png','Portable Network Graphics file (*.png)';...
 '*.tif','TIFF image (*.tif)';...
 '*.*',  'All Files (*.*)'},'Save As');
saveDataName = fullfile(PathName,FileName);
if(strcmpi(saveDataName(end-2:end),'eps'))
    saveas(gui.h0, saveDataName,'epsc');
else
    saveas(gui.h0, saveDataName);
end