function behavior_triggered_average(source,~)
    %
    % (C) Ann Kennedy, 2019
    % California Institute of Technology
    % Licensing: https://github.com/annkennedy/bento/blob/master/LICENSE.txt

    gui = guidata(source);
    hfig = figure();
    set(hfig,'dockcontrols','off','menubar','none',...
            'Tag','BTA browser','NumberTitle','off',...
            'Position',[550 70 600 720],'AutoResizeChildren','off','SizeChangedFcn',@resizeBTAwindow);
    gui.browser    = hfig;
    h.hfig = hfig;
    h.h0 = gui.h0;

    % plotting panel-------------------------------------------------------
    h.panelPlots = uipanel('parent',hfig,'units','pixels','position',[250 0 350 720],'bordertype','none');
    h.fig           = axes('parent',h.panelPlots,'Position',[0.1 0.65 0.875 0.27],'xtick',[]);
    title('Behavior-triggered average');
    hold on;
    h.figLine       = plot([0 0],get(gca,'ylim'),'k');
    % h.sc            = plot([0 0],[0 0],'k','linewidth',5);
    h.fig_sub       = axes('parent',h.panelPlots,'Position',[0.1 0.07  0.875 0.55],'xlim',[-10 10],'ytick',[]);
    xlabel('time (seconds)');
    hold on;
    h.figLineS      = plot([0 0],get(gca,'ylim'),'k');
    % h.scS           = plot([0 0],[0 0],'k','linewidth',5);
    h.isActive      = 1;

    % control panel--------------------------------------------------------
    h.panelCtrl        = uipanel('parent',hfig,'units','pixels','position',[0 0 250 720],'bordertype','none');
    drawnow;
    % adding a scrollbar to the panel, courtesy of undocumented Matlab:
    % Get the panel's underlying JPanel object reference
    jPanel = h.panelCtrl.JavaFrame.getGUIDEView.getParent;
    % Embed the JPanel within a new JScrollPanel object
    jScrollPanel = javaObjectEDT(javax.swing.JScrollPane(jPanel));
    % Remove the JScrollPane border-line
    jScrollPanel.setBorder([]);
    % Place the JScrollPanel in same GUI location as the original panel
    pixelpos = getpixelposition(h.panelCtrl);
    hParent = h.panelCtrl.Parent;
    [hjScrollPanel, hScrollPanel] = javacomponent(jScrollPanel, pixelpos, hParent);
    hScrollPanel.Units = 'norm';
    % Ensure that the scroll-panel and contained panel have linked visibility
    hLink = linkprop([h.panelCtrl,hScrollPanel],'Visible');
    setappdata(h.panelCtrl,'ScrollPanelVisibilityLink',hLink);

    bump    = 680;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Behavior trigger:',...
            'HorizontalAlignment','left',...
            'Position',[20 bump 120 30]);
    bump = bump - 18;
    h.bhv = uicontrol('parent',h.panelCtrl,'Style','popup',...
            'String',fieldnames(gui.annot.bhv),...
            'Value',1,...
            'Position',[30 bump 200 30],...
            'Callback',{@updateBTA,gui});
    bump = bump - 22;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','in channel:',...
            'HorizontalAlignment','left',...
            'Position',[30 bump 120 30]);
    bump = bump - 18;
    h.chTrig = uicontrol('parent',h.panelCtrl,'Style','popup',...
            'String',gui.annot.channels,...
            'Value',1,...
            'Position',[30 bump 200 30],...
            'Callback',{@updateBTA,gui});
    
    bump = bump - 18;
    h.toggle.start = uicontrol('parent',h.panelCtrl,'Style','radiobutton',...
            'String','Align at start',...
            'Value',1,...
            'Position',[50 bump 150 20],...
            'Callback',{@setBTAalign,gui,0});
    bump = bump - 20;
    h.toggle.end = uicontrol('parent',h.panelCtrl,'Style','radiobutton',...
            'String','Align at end',...
            'Value',0,...
            'Position',[50 bump 150 20],...
            'Callback',{@setBTAalign,gui,1});

    bump = bump - 40;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Window:',...
            'HorizontalAlignment','right',...
            'Position',[30 bump 50 30]);
    h.pre = uicontrol('parent',h.panelCtrl,'Style','edit',...
            'String','10',...
            'Position',[85 bump+10 40 25],...
            'Callback',{@resizeBTA,gui});
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','sec before',...
            'HorizontalAlignment','left',...
            'Position',[130 bump 60 30]);

    bump = bump - 30;
    h.post = uicontrol('parent',h.panelCtrl,'Style','edit',...
            'String','10',...
            'Position',[85 bump+10 40 25],...
            'Callback',{@resizeBTA,gui});
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','sec after',...
            'HorizontalAlignment','left',...
            'Position',[130 bump 60 30]);
        
    bump = bump - 30;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Bin size:',...
            'HorizontalAlignment','right',...
            'Position',[30 bump 50 30]);
    h.bin  = uicontrol('parent',h.panelCtrl,'Style','edit',...
            'String','0.25',...
            'Position',[85 bump+10 40 25],...
            'Callback',{@updateBTA,gui});
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','seconds',...
            'HorizontalAlignment','left',...
            'Position',[130 bump 60 30]);
        
        
    bump = bump - 30;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Discard bouts under',...
            'HorizontalAlignment','right',...
            'Position',[30 bump 105 30]);
    h.discard = uicontrol('parent',h.panelCtrl,'Style','edit',...
            'String','2',...
            'Position',[140 bump+10 40 25],...
            'Callback',{@updateBTA,gui});
    uicontrol('parent',h.panelCtrl,'Style','text',...
        'String','sec long',...
        'HorizontalAlignment','left',...
        'Position',[185 bump 70 30]);

    bump = bump - 30;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Merge bouts under',...
            'HorizontalAlignment','right',...
            'Position',[30 bump 105 30]);
    h.merge = uicontrol('parent',h.panelCtrl,'Style','edit',...
            'String','2',...
            'Position',[140 bump+10 40 25],...
            'Callback',{@updateBTA,gui});
    uicontrol('parent',h.panelCtrl,'Style','text',...
        'String','sec apart',...
        'HorizontalAlignment','left',...
        'Position',[185 bump 60 30]);

    bump = bump - 30;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Element to analyze:',...
            'HorizontalAlignment','left',...
            'Position',[20 bump 120 30]);
        
    bump = bump - 20;
    % Populating menu -----------------------------------------------------
    bhvlist = fieldnames(gui.annot.bhv);
    menuStr={};
    if(size(gui.data.rast,1))
        menuStr     = {'Population average'};
    end
    if(size(gui.data.rast,1))
        temp        = strcat('unit ',{' '},cellstr(num2str((1:size(gui.data.rast,1))')));
        menuStr     = {menuStr{:},temp{:}};
    end
    temp = strcat('behavior: ',{' '},bhvlist);
    menuStr = {menuStr{:},temp{:}};

    if(gui.enabled.features(1))
        for ch = gui.features.channels.String'
            feats = strcat('feature',{' '},num2str((1:length(gui.features.menu.String))'),...
                    ': ',{' '},gui.features.menu.String,{', '},ch{:});
            menuStr = {menuStr{:},feats{:}};
        end
    end

    h.unit = uicontrol('parent',h.panelCtrl,'Style','popup',...
            'String',menuStr,...
            'Value',1,...
            'Position',[30 bump 200 30],...
            'Callback',{@updateBTA,gui});
	
    bump = bump - 23;
    h.chAvgTxt = uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','in channel(s):',...
            'HorizontalAlignment','left',...
            'Position',[30 bump 120 30],'Enable','off');
    bump = bump - 18;
    h.chAvg = uicontrol('parent',h.panelCtrl,'Style','listbox',...
            'String',gui.annot.channels,...
            'Value',1,...
            'Min',1,'Max',length(gui.annot.channels)+1,...
            'Position',[30 bump 200 30],...
            'Callback',{@updateBTA,gui},'Enable','off');

    bump = bump - 32;
    h.trAvgTxt = uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','from trial(s):',...
            'HorizontalAlignment','left',...
            'Position',[30 bump 120 30],'Enable','off');
    bump = bump - 18;
    trials = splitlines(sprintf('mouse %d, session %d, trial %d\n',gui.allPopulated'));
    h.trAvg = uicontrol('parent',h.panelCtrl,'Style','listbox',...
            'String',trials(1:end-1),...
            'Value',1,...
            'Min',1,'Max',length(trials)-1,...
            'Position',[30 bump 200 30],...
            'Callback',{@updateBTA,gui},'Enable','off');
        
    bump = bump - 38;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Z-score traces:',...
            'HorizontalAlignment','left',...
            'Position',[30 bump 80 30]);
    h.zscore = uicontrol('parent',h.panelCtrl,'Style','checkbox',...
            'Value',0,...
            'Position',[110 bump+13 80 20],...
            'Callback',{@updateBTA,gui});
    %----------------------------------------------------------------------
    
    bump = bump - 25;
    uicontrol('parent',h.panelCtrl,'Style','text',...
            'String','Behaviors to show:',...
            'HorizontalAlignment','left',...
            'Position',[20 bump 150 30]);
    nbeh = length(bhvlist);
    ncol = 2;
    for j = 1:ceil(nbeh/ncol)
        bump = bump - 20;
        for i = 1:ncol
            b = (j-1)*ncol + i;
            if(b>nbeh)
                continue;
            end
            h.bhvrs(b) = uicontrol('parent',h.panelCtrl,'Style','checkbox',...
                    'Value',1,...
                    'Position',[30+(i-1)*120 bump+13 19 19],...
                    'CData',getButtonImage(gui.annot.cmap.(bhvlist{b}),1),...
                    'Tag',['checkbox_' strrep(bhvlist{b},'-','_')],...
                    'Callback',{@updateBTA,gui});
            uicontrol('parent',h.panelCtrl,'Style','text',...
                    'String',strrep(bhvlist{b},'_',' '),...
                    'HorizontalAlignment','left',...
                    'Position',[55+(i-1)*120 bump 80 30]);
        end
    end

    bump = bump - 30;
    uicontrol('parent',h.panelCtrl,'Style','pushbutton',...
            'String','Save Figure',...
            'Position',[157 bump 70 30],...
            'Callback',@saveBTA);
    uicontrol('parent',h.panelCtrl,'Style','pushbutton',...
            'String','Save BTA to Workspace',...
            'Position',[22 bump 130 30],...
            'Callback',{@outputBTA,gui});

    guidata(source,gui);
    guidata(hfig,h);
end

function resizeBTAwindow(source,~)
    if(isempty(source.Children))
        return;
    end
    source.Children(1).Position = [source.Children(1).Position(1:2) [250]/source.Position(3) 1];
    source.Children(3).Position = [source.Children(3).Position(1:2) source.Position(3)-300 source.Position(4)];
end