function getPCAxes(gui,source)
% ask the user which trials to use for PCA (and how many PCs to include?)

m       = gui.data.info.mouse;
sess    = gui.data.info.session;
use     = gui.allPopulated(:,1)==m & gui.allPopulated(:,2)==str2double(strrep(sess,'session',''));
trList  = gui.allPopulated(use,3);

stringList = {};
for tr = trList'
    stringList{end+1} = ['Trial ' num2str(tr)...
                         ' (' gui.allData(m).(sess)(tr).stim ')'];
end

h = figure('dockcontrols','off','menubar','none',...
    'Tag','PCA Setup','NumberTitle','off');
gui.browser = h;
p = get(h,'Position');
set(h,'Position',[p(1:2) 240 350]);


uicontrol('Style','text',...
            'String','Pick trials to use for finding principal axes (usually all)',...
            'Position',[20 275 200 60],...
            'fontsize',11);
trials = uicontrol('Style','listbox',...
            'HorizontalAlignment','left',...
            'Max',length(trList),...
            'String',stringList,...
            'Value',1:length(trList),...
            'Position', [20 140 200 150]);
uicontrol('Style','text','horizontalalign','left',...
            'String','# PCs to compute:',...
            'position',[30 80 100 40],...
            'fontsize',11);
nPCs        = uicontrol('Style','Edit',...
            'String','10',...
            'Position',[110 90 100 30],...
            'fontsize',11);
uicontrol('Style','text',...
            'String',['(max ' num2str(size(gui.data.rast,1)) ')'],...
            'position',[110 70 100 20]);
uicontrol('Style','pushbutton',...
            'String','Ok',...
            'position',[60 20 120 40],...
            'callback',{@doPCA,source,h,trials,nPCs,gui,m,sess,trList});