function setYawPitchRoll(source)
%
% (C) Ann Kennedy, 2019
% California Institute of Technology
% Licensing: https://github.com/annkennedy/bento/blob/master/LICENSE.txt


    gui         = guidata(source);
    

    h = figure('dockcontrols','off','menubar','none',...
        'Tag','Trace browser','NumberTitle','off','name','shift annot');
    h.Position(3:4) = [210 400];
    gui.browser = h;
    
    data.yaw = uicontrol('Style','slider',...
                'Position',[10 10 20 380],...
                'Min',-pi,'Max',pi,'Value',0,...
                'callback',{@setAngles,gui.h0});
    data.pitch = uicontrol('Style','slider',...
                 'Position',[40 10 20 380],...
                 'Min',-pi,'Max',pi,'Value',0,...
                'callback',{@setAngles,gui.h0'});
    data.roll = uicontrol('Style','slider',...
                 'Position',[70 10 20 380],...
                 'Min',-pi,'Max',pi,'Value',0,...
                'callback',{@setAngles,gui.h0});
    
	data.dx = uicontrol('Style','slider',...
                 'Position',[120 10 20 380],...
                 'Min',-1000,'Max',1000,'Value',0,...
                 'SliderStep',[1 20]/2000,...
                'callback',{@setAngles,gui.h0});
	data.dy = uicontrol('Style','slider',...
                 'Position',[150 10 20 380],...
                 'Min',-1000,'Max',1000,'Value',0,...
                 'SliderStep',[1 20]/2000,...
                'callback',{@setAngles,gui.h0});
	data.dz = uicontrol('Style','slider',...
                 'Position',[180 10 20 380],...
                 'Min',-1000,'Max',1000,'Value',0,...
                 'SliderStep',[1 20]/2000,...
                'callback',{@setAngles,gui.h0});
	guidata(h,data);
end


function setAngles(source,~,parent)
    gui = guidata(parent);
    data = guidata(source);
    gui.data.io.movie.angles = [data.yaw.Value, data.pitch.Value, data.roll.Value, ...
                                data.dx.Value, data.dy.Value, data.dz.Value];
    guidata(parent,gui);
    updatePlot(parent,[]);
end