function launchBTA(source,~)
%
% (C) Ann Kennedy, 2019
% California Institute of Technology
% Licensing: https://github.com/annkennedy/bento/blob/master/LICENSE.txt


parent      = source;

data = guidata(source);
hfig = figure('dockcontrols','off','menubar','none',...
        'Tag','BTA browser','NumberTitle','off',...
        'Position',[550 70 600 700],...
        'CloseRequestFcn',{'closeBrowser',parent});
    
data.browser    = hfig;
h.fig           = axes('Position',[0.43 0.65 0.53 0.27],'xtick',[],'ytick',[]);
hold on;
h.figLine       = plot([0 0],get(gca,'ylim'),'k');
% h.sc            = plot([0 0],[0 0],'k','linewidth',5);
h.fig_sub       = axes('Position',[0.43 0.07  0.53 0.55],'ytick',[],'xlim',[-10 10]);
hold on;
h.figLineS      = plot([0 0],get(gca,'ylim'),'k');
% h.scS           = plot([0 0],[0 0],'k','linewidth',5);
h.isActive      = 0;

bump    = 660;
uicontrol('Style','text',...
        'String','Behavior-triggered average',...
        'FontSize',10,'FontWeight','bold',...
        'Position',[0 bump 600 30]);

bump    = bump - 50;
uicontrol('Style','text',...
        'String','Behavior to analyze:',...
        'HorizontalAlignment','left',...
        'Position',[20 bump 120 30]);
bump = bump - 20;
h.bhv = uicontrol('Style','popup',...
        'String',data.lbls,...
        'Value',1,...
        'Position',[30 bump 200 30],...
        'Callback',{@updateBTA,data});
bump = bump - 25;
h.toggle.start = uicontrol('Style','radiobutton',...
        'String','Align at start',...
        'Value',1,...
        'Position',[50 bump 150 20],...
        'Callback',{@setBTAalign,data,0});
bump = bump - 22;
h.toggle.end = uicontrol('Style','radiobutton',...
        'String','Align at end',...
        'Value',0,...
        'Position',[50 bump 150 20],...
        'Callback',{@setBTAalign,data,1});

bump = bump - 50;
uicontrol('Style','text',...
        'String','Window:',...
        'HorizontalAlignment','right',...
        'Position',[30 bump 50 30]);
h.pre = uicontrol('Style','edit',...
        'String','10',...
        'Position',[85 bump+10 40 25],...
        'Callback',{@resizeBTA,data});
uicontrol('Style','text',...
        'String','sec before',...
        'HorizontalAlignment','left',...
        'Position',[130 bump 60 30]);

bump = bump - 30;
h.post = uicontrol('Style','edit',...
        'String','10',...
        'Position',[85 bump+10 40 25],...
        'Callback',{@resizeBTA,data});
uicontrol('Style','text',...
        'String','sec after',...
        'HorizontalAlignment','left',...
        'Position',[130 bump 60 30]);

bump = bump - 50;
uicontrol('Style','text',...
        'String','Discard bouts under',...
        'HorizontalAlignment','right',...
        'Position',[30 bump 105 30]);
h.discard = uicontrol('Style','edit',...
        'String','2',...
        'Position',[140 bump+10 40 25],...
        'Callback',{@updateBTA,data});
uicontrol('Style','text',...
    'String','sec long',...
    'HorizontalAlignment','left',...
    'Position',[185 bump 70 30]);

bump = bump - 30;
uicontrol('Style','text',...
        'String','Merge bouts under',...
        'HorizontalAlignment','right',...
        'Position',[30 bump 105 30]);
h.merge = uicontrol('Style','edit',...
        'String','2',...
        'Position',[140 bump+10 40 25],...
        'Callback',{@updateBTA,data});
uicontrol('Style','text',...
    'String','sec apart',...
    'HorizontalAlignment','left',...
    'Position',[185 bump 60 30]);

bump = bump - 50;
uicontrol('Style','text',...
        'String','Element to analyze:',...
        'HorizontalAlignment','left',...
        'Position',[20 bump 120 30]);
bump = bump - 20;

menuStr     = {'Population average'};
temp        = strcat('PC ',{' '},cellstr(num2str((1:size(data.PCs,1))')));
menuStr     = {menuStr{:},temp{:}};
temp        = strcat('unit ',{' '},cellstr(num2str((1:size(data.rast,1))')));
menuStr     = {menuStr{:},temp{:}};
h.unit = uicontrol('Style','popup',...
        'String',menuStr,...
        'Value',1,...
        'Position',[30 bump 200 30],...
        'Callback',{@updateBTA,data});

bump = bump - 40;
uicontrol('Style','text',...
        'String','Behaviors to show:',...
        'HorizontalAlignment','left',...
        'Position',[20 bump 150 30]);
nbeh = length(data.lbls);
ncol = 2;
for j = 1:ceil(nbeh/ncol)
    bump = bump - 25;
    for i = 1:ncol
        b = (j-1)*ncol + i;
        h.bhvrs(b) = uicontrol('Style','checkbox',...
                'Value',1,...
                'Position',[30+(i-1)*120 bump+13 20 20],...
                'CData',getButtonImage(data.cmap.(data.lbls{b}),1),...
                'Tag','checkbox',...
                'Callback',{@updateBTA,data});
        uicontrol('Style','text',...
                'String',strrep(data.lbls{b},'_',' '),...
                'HorizontalAlignment','left',...
                'Position',[50+(i-1)*120 bump 80 30]);
    end
end

bump = bump - 40;
uicontrol('Style','text',...
        'String','Zscore traces:',...
        'HorizontalAlignment','left',...
        'Position',[20 bump 80 30]);
h.zscore = uicontrol('Style','checkbox',...
        'Value',1,...
        'Position',[100 bump+13 80 20],...
        'Callback',{@updateBTA,data});


bump = bump - 40;
uicontrol('Style','pushbutton',...
        'String','Compute',...
        'Position',[95 bump 70 30],...
        'Callback',{@computeBTA,data});
bump = bump - 40;
uicontrol('Style','pushbutton',...
        'String','Clear',...
        'Position',[95 bump 70 30],...
        'Callback',@clearBTA);

guidata(source,data);
guidata(hfig,h);