function mh = menu_setup(gui)
%
% (C) Ann Kennedy, 2019
% California Institute of Technology
% Licensing: https://github.com/annkennedy/bento/blob/master/LICENSE.txt

pluginPath  = [fileparts(fileparts(mfilename('fullpath'))) filesep 'plugins'];
pluginFiles = dir(pluginPath);
pluginList = {pluginFiles.name}';
pluginList([pluginFiles.isdir] & ~cellfun(@isempty,strfind({pluginFiles.name},'.'))) = [];
pluginCalls = strcat(pluginList,'(gcf)');
pluginList = strcat('>',strrep(pluginList,'_',' '));

labels = char('&File',...
                 '>L&oad experiment^o',...
                 '>&Edit experiment^e',...
                 '>-------',...
                 '>Manage annotations',...
                 '>-------',...
                 '>Manage tracking data',...
                 '>Zoom movie in',...
                 '>Revert zoom',...
                 '>-------',...
                 '>Save screenshot',...
                 '>Save this movie frame',...
                 '>Save movie',...
                 '>-------',...
                 '>Quit',...
             '&Annotations',...
                 '>Set annotation &colors^c',...
                 '>Set annotation &hotkeys^h',...
                 '>Fix annot timing',...
                 '>Scale annot timing',...
                 '>Change annot framerate',...
                 '>Preferences...',...
             '&Display',...
                 '>Select &traces to show^t',...
                 '>Select a&nnotations to show^n',...
                 '>-------',...
                 '>Plot 2d projection',...
                 '>Clear 2d projection',...
                 '>-------',...
                 '>Rotate 3D keypoints',...
                 '>-------',...
                 '>Toggle object &visibility^v',...
                 '>-------',...
                 '>Adjust &audio scaling^a',...
                 '>Adjust &movie scaling^m',...
             '&Plugins',...
                 pluginList{:},...
             '&Help',...
                 '>Navigation s&hortcuts^h');
             
calls = char('','loadExpt(gcf,[],''load'')','loadExpt(gcf,[],''edit'')',...
             '','launchAnnotEditor(gcf,[])',...
             '','launchTrackingCleanup(gcf)','cropMovie(gcf,[],''crop'')','cropMovie(gcf,[],''revert'')',...
             '','saveScreen(gcf,0)','saveScreen(gcf,1)',...
                'saveMovie(gcf)',...
             '','doQuit(gcf)',...
             ...
             '','launchColorPick(gcf,[])',...
                'setAnnotHotkeys(gcf,[])',...
                'bumpAnnot(gcf)',...
                'scaleAnnot(gcf)',...
                'launchAnnoChanger(gcf)',...
                'setAnnotSaveType(gcf)',...
             '','pickUnits(gcf)','pickAnnot(gcf)',...
             '','setScatterDims(gcf)',...
                'clearScatterDims(gcf)',...
             '','setYawPitchRoll(gcf)',...
             '','toggleEnabled(gcf)','',...
                'setAudioThresholds(gcf)',...
                'setMovieBrightness(gcf)',...
             '',pluginCalls{:},...
             '','openHelpMenu(gcf)');

mh.display = makemenu(gui.h0,labels,calls);

% mh.analyze = uimenu(gui.h0,'Label','Analysis','enable','off');
% uimenu(mh.analyze,'Label','Find similar events','callback',{@(x,y) disp('not implemented yet')});