% function launchTrackingCleanup(source,~)

% gui = guidata(source);
% need a way to pass the current frame number in!

h.gui = gui;
h.fig = figure('dockcontrols','off','menubar','none',...
    'Tag','Tracking','name','Edit tracking data','NumberTitle','off');
gui.browser = h.fig;
p = get(h.fig,'Position');
set(h.fig,'Position',[p(1:2)+[160 0] 250 300]);

% box to set number of active elements
uicontrol('Style','text','horizontalalign','right',...
            'String','# objects being tracked',...
            'Units','normalized','Position',[.075 .825 .375 .125],...
            'fontsize',11);
h.bhv1 = uicontrol('Style','edit',...
            'String','0',...
            'Units','normalized','Position',[.55 .8375 .25 .1],...
            'fontsize',11,...
            'callback',@(src,evt,gui,ind)eval(['gui.data.tracking.active{ind}=1:' src.String ')']));

% buttons for easier frame-by-frame advance
uicontrol('Style','text','horizontalalign','right',...
            'String','Single-frame advance',...
            'Units','normalized','Position',[.075 .665 .375 .125],...
            'fontsize',11);
uicontrol('Style','pushbutton','String',char(9664),...
            'units','normalized','Position', [.515 .665 .15 .125],...
            'Callback',{@fineTrackingStep, 1},'fontsize',11);
uicontrol('Style','pushbutton','String',char(9654),...
            'units','normalized','Position', [.685 .665 .15 .125],...
            'Callback',{@fineTrackingStep,-1},'fontsize',11);

        
% button to switch two elements


% button to manually place an element


% button to crop frame/revert crop


% button to save your work to a file