function launchTrackingCleanup(source,~)
gui  = guidata(source);
time    = gui.ctrl.slider.Value;
frnum   = floor(time*gui.data.annoFR)+1;

h.guifig = gui.h0;
h.fig = figure('dockcontrols','off','menubar','none',...
    'Tag','Tracking','name','Edit tracking data','NumberTitle','off',...
    'WindowButtonUpFcn',@clearActionFromPopup);
h.Action=[];
gui.browser = h.fig;
p = get(h.fig,'Position');
set(h.fig,'Position',[p(1:2)+[160 0] 250 350]);

% box to set number of active elements
uicontrol('Style','text','horizontalalign','right',...
            'String','# objects being tracked',...
            'Units','normalized','Position',[.1 .84 .375 .1],...
            'fontsize',11);
h.bhv1 = uicontrol('Style','edit',...
            'String',num2str(max(gui.data.tracking.active{frnum})),...
            'Units','normalized','Position',[.6 .84 .25 .09],...
            'fontsize',11,...
            'callback',@setActivePoints);

% button to crop frame/revert crop
uicontrol('Style','pushbutton','String','Zoom movie',...
            'units','normalized','Position', [.125 .7 .4 .1],...
            'Callback',{@cropMovie,'crop'},'fontsize',11);
uicontrol('Style','pushbutton','String','Revert',...
            'units','normalized','Position', [.55 .7 .3 .1],...
            'Callback',{@cropMovie,'revert'},'fontsize',11);

% buttons for easier frame-by-frame advance
uicontrol('Style','pushbutton','String',char(171),...
            'units','normalized','Position', [.175 .3 .15 .1],'fontsize',11,...
            'Enable', 'inactive','ButtonDownFcn',{@fineTrackingStep, -1});
uicontrol('Style','pushbutton','String',char(9664),...
            'units','normalized','Position', [.35 .3 .15 .1],'fontsize',11,...
            'Enable', 'inactive','ButtonDownFcn',{@fineTrackingStep, -1/gui.data.io.movie.FR});
uicontrol('Style','pushbutton','String',char(9654),...
            'units','normalized','Position', [.5 .3 .15 .1],'fontsize',11,...
            'Enable', 'inactive','ButtonDownFcn',{@fineTrackingStep, 1/gui.data.io.movie.FR});
uicontrol('Style','pushbutton','String',char(187),...
            'units','normalized','Position', [.675 .3 .15 .1],'fontsize',11,...
            'Enable', 'inactive','ButtonDownFcn',{@fineTrackingStep, 1});

        
% button to switch two elements
h.swap1 =   uicontrol('Style','edit','String','',...
            'Units','normalized','Position',[.15 .42 .2 .09],...
            'fontsize',11);
h.swap2 =   uicontrol('Style','edit','String','',...
            'Units','normalized','Position',[.375 .42 .2 .09],...
            'fontsize',11);
uicontrol('Style','pushbutton','String','Swap',...
            'units','normalized','Position', [.6 .415 .25 .1],...
            'Callback',{@tracking_editLabels,'swap'},'fontsize',11);

% % buttons to manually place/delete an element
% uicontrol('Style','pushbutton','String','Add point',...
%             'units','normalized','Position', [.25 .55 .5 .1],...
%             'Callback',{@tracking_editLabels,'add'},'fontsize',11);


% button to save your work to a file
uicontrol('Style','pushbutton','String','Save changes',...
            'units','normalized','Position', [.25 .075 .5 .15],...
            'fontsize',11,'backgroundcolor',[.65 1 .65],...
            'Callback',@saveTrackingChanges);
        
guidata(h.fig,h);