function annot = drawannot(gui,row,scale,nRows)

annot.panel = uipanel('parent',gui.ctrl.panel,...
        'position',[0.01 (row-.5)/(nRows+1) 0.98 scale/(nRows+1)],'bordertype','none');

annot.ch = uicontrol('parent',annot.panel,'Style','popupmenu',...
            'String',{'-- pick channel --','add new...'},...
            'units','normalized','Position', [.15 0 .225 .8],...
            'Callback',{@updateFields,'channel'});
annot.annot = uicontrol('parent',annot.panel,'Style','popupmenu',...
            'String',{'-- pick label --','add new...'},...
            'units','normalized','Position', [.4 0 .225 .8],...
            'Callback',{@updateFields,'annot'});

load('icons.mat');
annot.toggleAnnot = uicontrol(annot.panel,'Style','togglebutton','CData',imgs.f1,'units','normalized',...
               'Tag','add','position',[.65 .05 .05 .8],'tooltip','Add annotation','Callback',@toggleAnnot);
annot.toggleErase = uicontrol(annot.panel,'Style','togglebutton','CData',imgs.f2,'units','normalized',...
               'Tag','remove','position',[.71 .05 .05 .8],'tooltip','Erase annotation','Callback',@toggleAnnot);
annot.save        = uicontrol(annot.panel,'Style','pushbutton','CData',imgs.f3,'units','normalized',...
               'position',[.79 .05 .05 .8],'tooltip','Save annotations','callback',@quickSave);