function annot = drawannot(gui,row,scale,nRows)

annot.panel = uipanel('parent',gui.ctrl.panel,...
        'position',[0.01 (row-.5)/(nRows+1) 0.98 scale/(nRows+1)],'bordertype','none');

uicontrol('parent',annot.panel,'Style','text',...
            'String','Channel','units','normalized','Position', [.025 0 .075 .7]);
annot.ch = uicontrol('parent',annot.panel,'Style','popupmenu',...
            'String',{''},'units','normalized','Position', [.1 0 .2 .8],...
            'Callback',@setChannel);
uicontrol('parent',annot.panel,'Style','pushbutton',...
            'String','Add','units','normalized','Position', [.305 0 .075 .8],...
            'Tag','add channel','Callback',@annotButtonHandler);
uicontrol('parent',annot.panel,'Style','pushbutton',...
            'String','Delete','units','normalized','Position', [.38 0 .075 .8],...
            'Tag','remove channel','Callback',@annotButtonHandler);
        
uicontrol('parent',annot.panel,'Style','text',...
            'String','Behaviors','units','normalized','Position', [.475 0 .1 .7]);
uicontrol('parent',annot.panel,'Style','pushbutton',...
            'String','Add','units','normalized','Position', [.58 0 .075 .8],...
            'Tag','add behavior','Callback',@annotButtonHandler);
uicontrol('parent',annot.panel,'Style','pushbutton',...
            'String','Delete','units','normalized','Position', [.655 0 .075 .8],...
            'Tag','remove behavior','Callback',@annotButtonHandler);

load('icons.mat');
annot.save        = uicontrol(annot.panel,'Style','pushbutton','CData',imgs.f3,'units','normalized',...
               'position',[.79 .05 .05 .8],'tooltip','Save annotations','callback',@quickSave);
           
annot.MARS        = uicontrol(annot.panel,'Style','pushbutton','string','MARS','units','normalized',...
               'position',[.85 0 .15 1],'backgroundcolor',[1 .75 .85],'callback',@MARSoptions);