function Kmeans_clustering(source)
%
% (C) Ann Kennedy, 2019
% California Institute of Technology
% Licensing: https://github.com/annkennedy/bento/blob/master/LICENSE.txt


% create a GUI to ask the users which trials from this animal/session we
% should use to do clustering:
gui = guidata(source);
m       = gui.data.info.mouse;
sess    = gui.data.info.session; 
use     = gui.allPopulated(:,1)==m & gui.allPopulated(:,2)==str2double(strrep(sess,'session',''));
trList  = gui.allPopulated(use,3); %the list of trial #s for this mouse/session

stringList = {};
for tr = trList'
    stringList{end+1} = [' ' num2str(tr) ') ' gui.allData(m).(sess)(tr).stim];
end

h.fig = figure('dockcontrols','off','menubar','none',...
    'Tag','Kmeans Setup','name','Clustering neurons','NumberTitle','off');
gui.browser = h.fig; %I'm not actually using gui.browser right now...
p = get(h.fig,'Position');
set(h.fig,'Position',[p(1:2)-[140 0] 280 360]);

h.ctrls     = uipanel('parent',h.fig,'position',[0 0 1 1],'bordertype','none');
h.ctrls2    = uipanel('parent',h.fig,'position',[0 0 1 1],'bordertype','none','visible','off');
h.output    = uipanel('parent',h.fig,'position',[1 0 0 1],'bordertype','none','visible','off');
h.sPlot     = axes('parent',h.output); % we'll use this to make a silhouette plot after running K-means

% prompt which trials to use:
uicontrol('Parent',h.ctrls,'Style','text','horizontalalign','left',...
            'String','Trials to use for clustering:',...
            'Units','normalized',...
            'Position',[.1 .895 1 .05],...
            'fontsize',10);
h.trials = uicontrol('Parent',h.ctrls,'Style','listbox',...
            'Max',length(stringList),...
            'String',stringList,'Value',1,...
            'Units','normalized',...
            'fontsize',10,...
            'Position',[.1 .48 .8 .4]);
        
% prompt for number of clusters:
uicontrol('Parent',h.ctrls,'Style','text','horizontalalign','right',...
            'String','Number of clusters:',...
            'Units','normalized',...
            'Position',[.1 .39 .5 .05],...
            'fontsize',10);
h.K     = uicontrol('Parent',h.ctrls,'Style','popup',...
            'String',num2str((2:50)'),...
            'Units','normalized',...
            'Position',[.65 .3975 .2 .05],...
            'fontsize',10);
        
visBhv = ~isempty(gui.annot.channels); % if there are annotations
%prompt whether to filter by behavior:
uicontrol('Parent',h.ctrls,'Style','text','horizontalalign','right',...
            'String','Use subset of frames:',...
            'Units','normalized',...
            'Position',[.1 .3 .5 .05],...
            'fontsize',10,'visible',visBhv);
h.subset = uicontrol('Parent',h.ctrls,'Style','checkbox',...
            'Value',0,...
            'Units','normalized',...
            'Position',[.7 .3 .26 .05],...
            'fontsize',10,'callback',@toggleKmeansSubframesVis,'visible',visBhv);
% pick that frame subset:
bhvList = [fieldnames(gui.annot.bhv); {'no label'}];

uicontrol('Parent',h.ctrls2,'Style','text','horizontalalign','center',...
            'String','Only use these frames:',...
            'Units','normalized',...
            'Position',[0 .835 .9 .05],...
            'fontsize',10,'visible',visBhv);
h.bhv  = uicontrol('Parent',h.ctrls2,'Style','listbox',...
            'Max',length(bhvList),...
            'String',bhvList,'Value',[],...
            'Units','normalized',...
            'Position',[0 .26 .9 .57],'visible',visBhv);
h.ch  = uicontrol('Parent',h.ctrls2,'style','popupmenu',...
            'String',[gui.annot.channels' {''}],...
            'units','normalized',...
            'position',[0 .14 .9 .1],'visible',visBhv);

%prompt whether to zscore traces:
uicontrol('Parent',h.ctrls,'Style','text','horizontalalign','right',...
            'String','Z-score data:',...
            'Units','normalized',...
            'Position',[.1 .225 .5 .05],...
            'fontsize',10);
h.zscore = uicontrol('Parent',h.ctrls,'Style','checkbox',...
            'Value',1,...
            'Units','normalized',...
            'Position',[.7 .225 .26 .05],...
            'fontsize',10);

% processKmeans will do the actual analysis:
h.go = uicontrol('Parent',h.ctrls,'Style','pushbutton','String','Go!',...
            'backgroundcolor',[.65 1 .65],...
            'units','normalized',...
            'position',[.1 .05 .8 .15],...
            'fontsize',10,...
            'callback',{@processKmeans,gui,m,sess,trList,bhvList});
guidata(gcf,h);

end

function toggleKmeansSubframesVis(source,~)
    h = guidata(source);
    w = get(h.ctrls,'Position'); w=w(3);
    sc = 200/(200+280);
    p = get(h.fig,'Position');
    if(source.Value)
        set(h.ctrls2,'Visible','on','Position',[w*(1-sc) 0 w*sc 1]);
        set(h.ctrls,'Position',[0 0 w*(1-sc) 1]);
        p(3) = p(3)+199;
        set(h.fig,'Position',p);
    else
        set(h.ctrls2,'Visible','off');
        set(h.ctrls,'Position',[0 0 w/(1-sc) 1]);
        p(3) = p(3)-199;
        set(h.fig,'Position',p);
    end
end